"""
Django settings for HomeRental project.
Configuration for home rental web application.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see:
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# ===== PATH CONFIGURATION =====
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ===== SECURITY SETTINGS =====
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^jfqx_ra3f5!_zp0#rr50cy5qav3sxx)hm*ob&v^_%4)3rm%5e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set to False in production

# Hosts/origins allowed for both HTTP and WebSocket traffic.
# Override in production with DJANGO_ALLOWED_HOSTS=example.com,www.example.com
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1,[::1]",
    ).split(",")
    if host.strip()
]


# ===== INSTALLED APPLICATIONS =====
# List of installed apps - order matters for apps with templates/static files
INSTALLED_APPS = [
    'django.contrib.admin',  # Django admin interface
    'django.contrib.auth',  # User authentication system
    'django.contrib.contenttypes',  # Content types framework
    'django.contrib.sessions',  # Session management
    'django.contrib.messages',  # Message framework for user notifications
    'daphne',  # Daphne provides the ASGI-aware runserver command used by Channels.
    'django.contrib.staticfiles',  # Static files management
    'channels',  # Django Channels for WebSocket support
    'chat',  # Accepted-booking chat app
    'home',
    'payments',  # Our home rental app
]

# ===== MIDDLEWARE CONFIGURATION =====
# Middleware processes requests and responses
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Security enhancements
    'django.contrib.sessions.middleware.SessionMiddleware',  # Session management
    'django.middleware.common.CommonMiddleware',  # Common utilities
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # User authentication
    'django.contrib.messages.middleware.MessageMiddleware',  # Message display
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking protection
]

# ===== URL CONFIGURATION =====
ROOT_URLCONF = 'HomeRental.urls'  # Root URL configuration
ASGI_APPLICATION = 'HomeRental.asgi.application'  # ASGI app used by Channels/uvicorn

# ===== TEMPLATE CONFIGURATION =====
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Global templates directory
        'APP_DIRS': True,  # Look for templates in app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Adds request to context
                'django.contrib.auth.context_processors.auth',  # Adds user to context
                'django.contrib.messages.context_processors.messages',  # Adds messages to context
                'home.context_processors.unread_notifications_count',  # Custom context processor for notifications
            ],
        },
    },
]

# ===== WSGI APPLICATION =====
WSGI_APPLICATION = 'HomeRental.wsgi.application'  # WSGI application for web servers


# ===== CHANNELS / WEBSOCKETS =====
# Default to an in-memory layer for local development. Set CHANNEL_REDIS_URL in
# production to use a shared Redis-backed layer across multiple workers.
CHANNEL_REDIS_URL = os.environ.get("CHANNEL_REDIS_URL", "").strip()

if CHANNEL_REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [CHANNEL_REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# ===== DATABASE CONFIGURATION =====
# Use SQLite for local development by default.
# Switch to MySQL by setting DB_ENGINE=mysql (or DB_NAME) plus DB_* variables.
DB_ENGINE = os.environ.get("DB_ENGINE", "").strip().lower()
DB_NAME = os.environ.get("DB_NAME", "").strip()

if DB_ENGINE in {"mysql", "django.db.backends.mysql"} or DB_NAME:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": DB_NAME or "home_rental",
            "USER": os.environ.get("DB_USER", "root"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
            "PORT": os.environ.get("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }



# ===== PASSWORD VALIDATION =====
# Password validators to enforce strong passwords
AUTH_PASSWORD_VALIDATORS = [
    {
        # Check password doesn't match user attributes (username, email)
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Minimum password length (default: 8 characters)
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # Check against top 20,000 common passwords
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Check password isn't entirely numeric
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ===== INTERNATIONALIZATION SETTINGS =====
# Language and timezone configuration
LANGUAGE_CODE = 'en-us'  # Default language

TIME_ZONE = 'UTC'  # Default timezone (change to your timezone if needed)

USE_I18N = True  # Enable i18n framework

USE_TZ = True  # Use timezone-aware datetime


# ===== STATIC FILES CONFIGURATION =====
# CSS, JavaScript, Images served by web server
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'  # URL prefix for static files
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Additional static files directories


# ===== MEDIA FILES CONFIGURATION =====
# User-uploaded files (images, documents, etc.)
MEDIA_URL = '/media/'  # URL prefix for media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Physical location of media files


# ===== AUTHENTICATION SETTINGS =====
LOGIN_URL = '/accounts/login'  # URL to redirect to for login

LOGIN_REDIRECT_URL = '/home/'  # URL to redirect to after successful login
LOGOUT_REDIRECT_URL = '/home/'  # URL to redirect to after logout


# for the email settings 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'shriram77890@gmail.com'       # Your Gmail
EMAIL_HOST_PASSWORD = 'yaxr gdas ipss vksj'      # Use App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# for the payment methods 
ESEWA_MERCHANT_ID = "EPAYTEST"
ESEWA_SECRET_KEY = os.environ.get("ESEWA_SECRET_KEY", "8gBm/:&EnhH.1/q")
ESEWA_SIGNED_FIELD_NAMES = os.environ.get(
    "ESEWA_SIGNED_FIELD_NAMES",
    "total_amount,transaction_uuid,product_code",
)
ESEWA_FORM_URL = os.environ.get(
    "ESEWA_FORM_URL",
    "https://rc-epay.esewa.com.np/api/epay/main/v2/form",
)

SUCCESS_URL = "http://127.0.0.1:8000/payment/success/"
FAILURE_URL = "http://127.0.0.1:8000/payment/failure/"
