# Generated by Django 6.0.1 on 2026-02-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
