# Generated by Django 6.0.2 on 2026-03-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=5,
            ),
        ),
    ]
