# Generated by Django 6.0.1 on 2026-03-18 04:53

import django.db.models.deletion
from django.db import migrations, models


def backfill_booking_status_and_acceptance_links(apps, schema_editor):
    Booking = apps.get_model("home", "Booking")
    BookingAcceptanceNotification = apps.get_model(
        "home",
        "BookingAcceptanceNotification",
    )

    for booking in Booking.objects.all().iterator():
        booking.status = "ACCEPTED" if booking.is_accepted else "PENDING"
        booking.save(update_fields=["status"])

    for notification in BookingAcceptanceNotification.objects.filter(
        booking__isnull=True
    ).iterator():
        accepted_booking = (
            Booking.objects.filter(
                property_id=notification.property_id,
                booked_by_id=notification.tenant_id,
                owner_id=notification.owner_id,
                status="ACCEPTED",
            )
            .order_by("-booked_at")
            .first()
        )
        if accepted_booking:
            notification.booking_id = accepted_booking.id
            notification.save(update_fields=["booking"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='bookingacceptancenotification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_acceptance_notifications', to='home.booking'),
        ),
        migrations.RunPython(
            backfill_booking_status_and_acceptance_links,
            noop_reverse,
        ),
    ]
