# Generated by Django 6.0.2 on 2026-03-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_booking_status_bookingacceptancenotification_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingacceptancenotification',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingacceptancenotification',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bookingacceptancenotification',
            name='property',
        ),
        migrations.RemoveField(
            model_name='bookingacceptancenotification',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='bookingcancellationnotification',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bookingcancellationnotification',
            name='property',
        ),
        migrations.RemoveField(
            model_name='bookingcancellationnotification',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingAcceptanceNotification',
        ),
        migrations.DeleteModel(
            name='BookingCancellationNotification',
        ),
        migrations.RunSQL(
            sql=[
                'DROP TABLE IF EXISTS "chat_chatmessage";',
                'DROP TABLE IF EXISTS "chat_message";',
                'DROP TABLE IF EXISTS "chat_chat_participants";',
                'DROP TABLE IF EXISTS "chat_chat";',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
