"""
Django settings for HomeRental project.
Configuration for home rental web application.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see:
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# ===== PATH CONFIGURATION =====
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ===== SECURITY SETTINGS =====
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^jfqx_ra3f5!_zp0#rr50cy5qav3sxx)hm*ob&v^_%4)3rm%5e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set to False in production

# Hosts/origins allowed for both HTTP and WebSocket traffic.
# Override in production with DJANGO_ALLOWED_HOSTS=example.com,www.example.com
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1,[::1]",
    ).split(",")
    if host.strip()
]


# ===== INSTALLED APPLICATIONS =====
# List of installed apps - order matters for apps with templates/static files
INSTALLED_APPS = [
    'django.contrib.admin',  # Django admin interface
    'django.contrib.auth',  # User authentication system
    'django.contrib.contenttypes',  # Content types framework
    'django.contrib.sessions',  # Session management
    'django.contrib.messages',  # Message framework for user notifications
    'django.contrib.staticfiles',  # Static files management
    'channels',  # Django Channels for WebSocket support
    'chat',  # Accepted-booking chat app
    'home',  # Our home rental app
]

# ===== MIDDLEWARE CONFIGURATION =====
# Middleware processes requests and responses
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Security enhancements
    'django.contrib.sessions.middleware.SessionMiddleware',  # Session management
    'django.middleware.common.CommonMiddleware',  # Common utilities
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # User authentication
    'django.contrib.messages.middleware.MessageMiddleware',  # Message display
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking protection
]

# ===== URL CONFIGURATION =====
ROOT_URLCONF = 'HomeRental.urls'  # Root URL configuration
ASGI_APPLICATION = 'HomeRental.asgi.application'  # ASGI app used by Channels/uvicorn

# ===== TEMPLATE CONFIGURATION =====
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Global templates directory
        'APP_DIRS': True,  # Look for templates in app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Adds request to context
                'django.contrib.auth.context_processors.auth',  # Adds user to context
                'django.contrib.messages.context_processors.messages',  # Adds messages to context
                'home.context_processors.unread_notifications_count',  # Custom context processor for notifications
            ],
        },
    },
]

# ===== WSGI APPLICATION =====
WSGI_APPLICATION = 'HomeRental.wsgi.application'  # WSGI application for web servers


# ===== CHANNELS / WEBSOCKETS =====
# Default to an in-memory layer for local development. Set CHANNEL_REDIS_URL in
# production to use a shared Redis-backed layer across multiple workers.
CHANNEL_REDIS_URL = os.environ.get("CHANNEL_REDIS_URL", "").strip()

if CHANNEL_REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [CHANNEL_REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# ===== DATABASE CONFIGURATION =====
# SQLite database configuration (suitable for development)
# Change to PostgreSQL or MySQL for production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # SQLite database engine
        'NAME': BASE_DIR / 'db.sqlite3',  # Database file location
    }
}


# ===== PASSWORD VALIDATION =====
# Password validators to enforce strong passwords
AUTH_PASSWORD_VALIDATORS = [
    {
        # Check password doesn't match user attributes (username, email)
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Minimum password length (default: 8 characters)
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # Check against top 20,000 common passwords
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Check password isn't entirely numeric
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ===== INTERNATIONALIZATION SETTINGS =====
# Language and timezone configuration
LANGUAGE_CODE = 'en-us'  # Default language

TIME_ZONE = 'UTC'  # Default timezone (change to your timezone if needed)

USE_I18N = True  # Enable i18n framework

USE_TZ = True  # Use timezone-aware datetime


# ===== STATIC FILES CONFIGURATION =====
# CSS, JavaScript, Images served by web server
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'  # URL prefix for static files
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Additional static files directories


# ===== MEDIA FILES CONFIGURATION =====
# User-uploaded files (images, documents, etc.)
MEDIA_URL = '/media/'  # URL prefix for media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Physical location of media files


# ===== AUTHENTICATION SETTINGS =====
LOGIN_URL = '/accounts/login'  # URL to redirect to for login

LOGIN_REDIRECT_URL = '/home/'  # URL to redirect to after successful login
LOGOUT_REDIRECT_URL = '/home/'  # URL to redirect to after logout


# ===== EMAIL CONFIGURATION =====
# Uses Django's built-in email backend (SMTP). If EMAIL_HOST is not set,
# emails are printed to the console (useful for development).
#
# Configure via environment variables (examples):
# - Gmail SMTP:
#   EMAIL_HOST=smtp.gmail.com
#   EMAIL_PORT=587
#   EMAIL_USE_TLS=1
#   EMAIL_HOST_USER=you@gmail.com
#   EMAIL_HOST_PASSWORD=your_app_password
# - SendGrid SMTP:
#   EMAIL_HOST=smtp.sendgrid.net
#   EMAIL_PORT=587
#   EMAIL_USE_TLS=1
#   EMAIL_HOST_USER=apikey
#   EMAIL_HOST_PASSWORD=your_sendgrid_api_key
EMAIL_HOST = os.environ.get("EMAIL_HOST", "").strip()
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "1").lower() not in ("0", "false", "no")
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "0").lower() in ("1", "true", "yes")
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "Ghar Setu <no-reply@gharsetu.local>",
)

if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    # Safe default for local development (prints emails to the console)
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
