# Generated by Django 6.0.2 on 2026-03-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_booking_chat_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["is_read"], name="chat_chatme_is_read_97dd73_idx"),
        ),
    ]
